Nextflow conversion
LiuzLab/AI_MARRVEL pull request #18
Opened 2024-06-10 18:06 UTC by hyunhwan-bcm

The PR includes numerous changes and should be carefully reviewed. @sasidharPasupuleti and @ZaahidShaik, please try to run this PR and verify its functionality. It would be beneficial to test it against a previously completed run.

## The PR Summary
- [x] convert the pipeline to a nextflow version
- [x] add error handling strategy 
- [x] output test 
- [ ] code review
- [ ] code optimization 

## How to use (or test)

Here is  an example:

```
nextflow run main.nf --run_id 12345 --ref_ver "hg19" --outdir testout_061024 \
                                    --input_hpo /home/hwan/AI_MARRVEL/test_data/hpos.txt \
                                    --input_vcf /home/hwan/AI_MARRVEL/test_data/demo.vcf.gz \
                                    --ref_dir /home/hwan/aim_data_dependencies_04_24_2024_sasi
```

You can also change the parameters in `nextflow.config` - you can run `nextflow run main.nf`

2024-06-28 19:00 UTC, jylee-bcm requested changes
I think `nextflow.config` should contain different values for each environment, so I'd like to include it into `.gitignore`. For the details, please read the comment on related code.

2024-06-28 19:00 UTC, jylee-bcm commented on scripts/proc.sh
If it's not used anymore, let's remove it

2024-06-28 19:00 UTC, jylee-bcm commented on nextflow.config
* Rename `nextflow.config` to `nextflow.config.example`
* Add `nextflow.config` to `.gitignore` list
* `nextflow.config.example `contain an instruction saying: Use this example file to create nextflow.config and change the values for: ref_dir, input_vcf, input_hpo`

2024-06-28 19:00 UTC, jylee-bcm commented on .gitignore
Add nextflow.config

2024-07-10 18:46 UTC, hyunhwan-bcm commented
@jylee-bcm please review my latest commit to this branch.

2024-07-12 15:36 UTC, jylee-bcm reviewed
I think it's better to remove /run/ directory, so that git can track the difference.
I will upload PR for it.

2024-07-12 15:59 UTC, hyunhwan-bcm commented
I thought I remove them, but it wasn't pushed. I am fine that if you delete the directory.

2024-07-12 16:46 UTC, jylee-bcm commented on utils/run_diff.py
Is it actively used? if not, remove it

2024-07-12 16:47 UTC, jylee-bcm commented
> I thought I remove them, but it wasn't pushed. I am fine that if you delete the directory.
You were right, just git couldn't track the difference.

2024-07-12 16:47 UTC, hyunhwan-bcm commented
You can remove it just for comparison of every column of dataframes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jaeyeon Lee ***@***.***>
Sent: Friday, July 12, 2024 11:46:43 AM
To: LiuzLab/AI_MARRVEL ***@***.***>
Cc: Jeong, Hyun-Hwan ***@***.***>; Author ***@***.***>
Subject: Re: [LiuzLab/AI_MARRVEL] Nextflow conversion (PR #18)

***CAUTION:*** This email is not from a BCM Source. Only click links or open attachments you know are safe.
________________________________

@jylee-bcm commented on this pull request.

________________________________

On utils/run_diff.py<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LiuzLab_AI-5FMARRVEL_pull_18-23discussion-5Fr1676191866&d=DwMFaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=-lih8OIo66XtgJH6zqJrfjIwRtqkkhDYbiD5mmg9N6M&m=2XM5e49yxOQhs1NNB4SFoGxj8unTaRLRVGntuz7wnTDY0WvZgWrEuhHM-xf7btMe&s=CdcZ_jtWIDD_2TTxmQ-_uEx2wfQOROk4kegA_jx-4T4&e=>:

Is it actively used? if not, remove it

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LiuzLab_AI-5FMARRVEL_pull_18-23pullrequestreview-2D2175324846&d=DwMFaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=-lih8OIo66XtgJH6zqJrfjIwRtqkkhDYbiD5mmg9N6M&m=2XM5e49yxOQhs1NNB4SFoGxj8unTaRLRVGntuz7wnTDY0WvZgWrEuhHM-xf7btMe&s=bBMfWwWhnMxRg3npFSHUehyCkqgCx2jq4VKJsAVZqh8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BHZAYJCDHCVNBEOBD4ZZX73ZMAB7HAVCNFSM6AAAAABJCZNYZSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNZVGMZDIOBUGY&d=DwMFaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=-lih8OIo66XtgJH6zqJrfjIwRtqkkhDYbiD5mmg9N6M&m=2XM5e49yxOQhs1NNB4SFoGxj8unTaRLRVGntuz7wnTDY0WvZgWrEuhHM-xf7btMe&s=NnDYkt65T14WXrysptKP-JYiLilodoZWFnLhVKKvRvc&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-07-12 17:38 UTC, jylee-bcm approved these changes
LGTM

2024-08-02 15:27 UTC, merged