Update VarTierDiseaseDBFalse.R
LiuzLab/AI_MARRVEL pull request #39
Opened 2024-07-27 04:48 UTC by hyunhwan-bcm

`VarTierDiseaseDBFalse.R` is the bottleneck for the current pipeline. This PR contains the updated  `VarTierDiseaseDBFalse.R`  from the current `nextflow_branch`, this will help to resolve the processing delay issue.

2024-07-27 04:49 UTC, hyunhwan-bcm commented
@jylee-bcm can you test this on both hg19/hg38? Thank you, we may need to use a small input for it.

2024-07-28 23:42 UTC, jylee-bcm commented on run/VarTierDiseaseDBFalse.R
> +omim_inheritance <- file.path(paste0("var_tier/", refg, "/genemap2.Inh.F.txt"))
`paste0('/run/data_dependencies/var_tier/',refg,'/genemap2.Inh.F.txt')`

2024-07-29 20:16 UTC, jylee-bcm requested changes
I will update the pr soon :D

2024-07-29 20:16 UTC, jylee-bcm commented on run/VarTierDiseaseDBFalse.R
> +genemap2.Inh.F <- readr::read_tsv(omim_inheritance)
use path()

2024-07-29 20:16 UTC, jylee-bcm commented on run/VarTierDiseaseDBFalse.R
> +  out.f,
use path()

2024-07-30 15:06 UTC, jylee-bcm approved these changes
Now it's working, but I could not perform the checking on outputs yet.

2024-08-16 21:30 UTC, hyunhwan-bcm commented
will be merged with `nextflow_conversion`

2024-08-16 21:30 UTC, closed without merging